const storyData = [
  { "id": "1", "background": "img/bg_livingroom.png", "speaker": "", "text": "C'est les vacances.\n\nSophie et Alexandre sont affalés sur le canapé. La console est allumée, les chips sont ouvertes, et personne n'a envie de bouger." },
  { "id": "2", "speaker": "", "text": "Alexandre attrape la manette." },
  { "id": "3", "speaker": "Alexandre", "text": "« On fait quoi ? »" },
  { "id": "4", "speaker": "Sophie", "text": "« GTA. »" },
  { "id": "5", "speaker": "Alexandre", "text": "« Ok. »" },
  { "id": "6", "speaker": "", "text": "Il lance le jeu. Le logo tourne. La musique démarre. Et là, en bas du menu, une ligne qu'ils n'avaient pas vue avant :" },
  { "id": "7", "speaker": "SYSTÈME", "text": "▶  HISTOIRE\n   MULTIJOUEUR\n   PARAMÈTRES\n▶  PROJET HEIST — MISSION SPÉCIALE [NOUVEAU]" },
  { "id": "8", "speaker": "Sophie", "text": "« C'est quoi ça ? » dit Sophie en se redressant." },
  { "id": "9", "speaker": "Alexandre", "text": "« Sais pas. »" },
  { "id": "10", "speaker": "Sophie", "text": "« On a rien téléchargé. »" },
  { "id": "11", "speaker": "Alexandre", "text": "« Bah... on regarde ? »" },
  { "id": "12", "speaker": "", "text": "Sophie hésite une seconde. Elle pense au Minecraft. Elle sait pas pourquoi, elle pense au Minecraft." },
  { "id": "13", "speaker": "Alexandre", "text": "« ...On appuie. »" },
  { "id": "14", "speaker": "", "text": "L'écran devient noir. Puis blanc. Et ce son — ce vrombissement sourd, cette vibration dans tout le corps — Sophie le reconnaît avant même d'avoir rouvert les yeux." },
  { "id": "15", "speaker": "Sophie", "text": "« Non. »" },
  { "id": "16", "speaker": "Alexandre", "text": "« ...Oh non. »" },
  { "id": "17", "background": "img/bg_lossantos.png", "speaker": "", "text": "Quand ils rouvrent les yeux, ils sont debout sur un trottoir de Los Santos.\nNéons, bitume chaud, voitures qui hurlent au feu rouge. Le soleil tape fort." },
  { "id": "18", "speaker": "", "text": "Leurs mains sont pixelisées aux jointures. Leurs vêtements ont changé — veste noire, gants fins, oreillette dans l'oreille gauche." },
  { "id": "19", "speaker": "Alexandre", "text": "« On est dans GTA. »" },
  { "id": "20", "speaker": "Sophie", "text": "« Ouais. »" },
  { "id": "21", "speaker": "Alexandre", "text": "« Pour de vrai. »" },
  { "id": "22", "speaker": "Sophie", "text": "« Ouais Alexandre. »" },
  { "id": "23", "speaker": "", "text": "Il ouvre la bouche. Sophie lui met un coup dans l'épaule avant qu'il dise quoi que ce soit." },
  { "id": "24", "speaker": "SYSTÈME", "text": "Bienvenue dans PROJET HEIST.\nVous êtes désormais joueurs actifs.\nRègle n°1 : ici, la logique du vrai monde s'applique.\nLes maths, les unités, le raisonnement... tout est réel." },
  { "id": "25", "speaker": "SYSTÈME", "text": "Règle n°2 : chaque erreur a des conséquences.\nRègle n°3 : il n'y a pas de règle n°3. Bonne chance." },
  { "id": "26", "speaker": "Alexandre", "text": "« \"La logique du vrai monde s'applique\"... C'est exactement ce que disait le vieux dans Minecraft. »" },
  { "id": "27", "speaker": "Sophie", "text": "« Je sais. »" },
  { "id": "28", "speaker": "", "text": "Une voix grésille dans leur oreillette. Nasillarde, un peu fatiguée, le genre de voix de quelqu'un qui a expliqué la même chose beaucoup trop de fois." },
  { "id": "29", "speaker": "Lester", "text": "« Ah. Vous êtes là. Bien. Lester. C'est comme ça qu'on m'appelle ici. Mon vrai nom... on s'en fout pour l'instant. »" },
  { "id": "30", "speaker": "Lester", "text": "« Le vieux de Minecraft m'a prévenu que vous arriviez. On se connaît. On a un groupe WhatsApp les PNJ. C'est pas votre problème. »" },
  { "id": "31", "speaker": "Lester", "text": "« Voilà ce que vous devez savoir : vous voulez rentrer chez vous ? Vous finissez le braquage. La Maze Bank Tower. Coffre n°7. »" },
  { "id": "32", "speaker": "Lester", "text": "« Vous entrez, vous prenez ce qu'il y a dedans, vous sortez. »" },
  { "id": "33", "speaker": "", "text": "Bruit de clavier dans l'oreillette." },
  { "id": "34", "speaker": "Lester", "text": "« Y'a des gardes, des caméras, une alarme qui répond en 4 minutes. Et vous deux comme équipe. »" },
  { "id": "35", "speaker": "Sophie", "text": "« On a fait avec moins. »" },
  { "id": "36", "speaker": "SYSTÈME", "text": "📁 BRIEFING — ACTE 1 : PRÉPARATION\nCible : Maze Bank Tower — Coffre n°7\nNiveau de sécurité : ████████░░ ÉLEVÉ\nTemps estimé : 20 minutes\nÉquipe : 2 personnes" },
  { "id": "37", "speaker": "Lester", "text": "« Première épreuve. Maintenant. »" },
  { "id": "38", "speaker": "", "text": "Sophie et Alexandre se regardent." },
  { "id": "39", "speaker": "Sophie", "text": "« Ok. »" },
  { "id": "40", "speaker": "Alexandre", "text": "« Ok. »" },
  { "id": "41", "speaker": "SYSTÈME", "text": "Quelque part dans un village pixelisé, un vieux PNJ lève son verre. Il savait que vous reviendriez." },
  { "id": "42", "speaker": "Lester", "text": "« Avant d'aller où que ce soit, vous avez besoin de cash. GTA$. Pas des euros, pas des bitcoins, des GTA$. »" },
  { "id": "43", "speaker": "Lester", "text": "« J'vous envoie 1 500€. C'est tout ce que j'ai de liquide. Vous les changez, vous achetez le matériel, et vous revenez me voir. »" },
  { "id": "44", "speaker": "Lester", "text": "« Y'a un bureau de change à deux rues d'ici. Le Lucky Exchange. Enfin... ce qu'il en reste. »" },
  { "id": "45", "speaker": "", "text": "Un silence." },
  { "id": "46", "speaker": "Lester", "text": "« Il vient de se faire braquer. Ouais. Ce matin. Timing parfait. »" },
  { "id": "47", "speaker": "SYSTÈME", "text": "[OBJECTIF MIS À JOUR]\nConvertir 1 500€ en GTA$.\nTemps disponible : 1h in-game / 15 minutes réelles.\nAttention : toute erreur de calcul affecte votre budget matériel." },
  { "id": "48", "background": "img/Acte 1 - bureaux de change.png", "speaker": "", "text": "Vous poussez la porte du Lucky Exchange." },
  { "id": "49", "speaker": "", "text": "Le lieu est dans un état catastrophique. Des papiers partout. Une vitre fissurée. Un affichage principal arraché du mur — il n'en reste que le cadre vide." },
  { "id": "50", "speaker": "", "text": "Derrière le comptoir, un homme vous regarde arriver. Il sourit un peu trop largement." },
  { "id": "51", "speaker": "Gérant", "text": "« Eh, bienvenus bienvenus. Pas le meilleur moment pour passer, comme vous voyez... mais je suis encore là, moi. Le seul bureau de change ouvert du quartier aujourd'hui. »" },
  { "id": "52", "speaker": "Gérant", "text": "« Taux du jour : 1€ = 1,1 GTA$. Commission : 5% standard. Les meilleurs prix de Los Santos, je vous jure sur ma mère. »" },
  { "id": "53", "speaker": "", "text": "Il pose ses mains sur le comptoir et attend. Vous regardez autour de vous." },
  { "id": "54", "background": "img/acte1 - ticket.png", "speaker": "", "text": "Par terre, un reçu froissé. Vous le ramassez discrètement." },
  { "id": "55", "background": "img/Acte 1 - affiche taux.png", "speaker": "", "text": "Sur le mur de gauche, une pancarte à moitié brûlée. Certains mots sont encore lisibles." },
  { "id": "56", "speaker": "", "text": "Votre téléphone in-game vibre." },
  { "id": "57", "background": "img/Acte 1 - téléphone.png", "speaker": "", "text": "Une vieille conversation WhatsApp d'un contact inconnu s'affiche — probablement un ancien client." },
  { "id": "58", "background": "img/Acte 1 - bureaux de change.png", "speaker": "Lester", "text": "« J'ai fouillé les archives du réseau. Avant le braquage de ce matin : 300€ donnaient 390 GTA$, commission incluse. La commission, elle a pas bougé depuis 2019. »" },
  { "id": "59", "speaker": "Lester", "text": "« Le mec vous ment sur au moins deux choses. À vous de trouver lesquelles. »" },
  { "id": "60", "speaker": "SYSTÈME", "text": "MODE DÉTECTIVE ACTIVÉ :\nCherchez des indices pour découvrir les mensonges du gérant ! (Cliquez sur l'écran pour fouiller et au centre pour affronter le Gérant en choisissant une réponse finale)" },
  {
    "id": "61",
    "type": "investigation",
    "background": "img/bg_exchange_interior.png",
    "hotspots": [
      { "type": "clue", "x": "40%", "y": "80%", "w": "15%", "h": "15%", "image": "img/acte1 - ticket.png" },
      { "type": "clue", "x": "1%", "y": "30%", "w": "20%", "h": "45%", "image": "img/Acte 1 - affiche taux.png" },
      { "type": "clue", "x": "75%", "y": "55%", "w": "10%", "h": "15%", "image": "img/Acte 1 - téléphone.png" },
      { "type": "action", "x": "35%", "y": "25%", "w": "30%", "h": "30%", "actionId": "riddle_1" }
    ]
  }
];
